### ISSUE TITLE
loss file?

### ISSUE THREAD

**Issue by zhyc9de** [simoncos/lola#2]
in file`data_preprocess.py`,line `from statics import champions`,i can't find `statics` in project,so...where can can i find it?

**Comment by simoncos** [comment]
Hi dude,

Thanks for the feedback. Would fix soon. Besides, can I know if you have gone through the crawling part with no problems?

**Comment by zhyc9de** [comment]
Thank u for u project,i will watch it
i have run `data_crawl.py` with some simple problem but solve them finally
eg. where u have marked [fix](https://github.com/simoncos/lola/blob/master/data_crawl.py#L109)
And at beginning,i don't know what is `summoner_id`,i find it in this [site](http://www.lolking.net/).i think use `summoner name` will be better?
look forward to a better readme

**Comment by simoncos** [comment]
closed with fix: https://github.com/simoncos/lola/commit/3d0bc0e144478210f9519a9d55b7a817a7c9b467

**Comment by simoncos** [comment]
@zhyc9de @LINK3599 I have fixed this problem, but note this is only a temporary one. 

I plan to find a better way to handle static information (about champions or so) in future, because I hope this project can be run online. So it's important to  maintain and update the database as the game's edition changes. 

If you have some nice ideas, do not hesitate to contact me.
